### PR TITLE
Add changelog for 0.63.4

### PR DESCRIPTION
**Pull request by kelset**
Adding changelog for 0.63.4 plus a super minor fix picked up by `yarn format`.

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
LGTM for whatever that's worth :-)
Thanks @kelset - happy to have the missing bundle for current gradle fix in there!

**Comment by kelset** [comment]
Thanks @mikehardy! Super worth, I'll proceed with merging :) thanks for checking it!

**Comment by nickfujita** [comment]
@kelset @mikehardy 
Thanks for putting this together and merging. Was wondering if either of you might know who to get in contact with to have this patch version updated on the Walmart Labs hosted Android Maven repo?
https://mvnrepository.com/artifact/com.walmartlabs.ern/react-native

**Comment by kelset** [comment]
@nickfujita no idea, sorry - this is actually the first time I'm hearing of those artifacts 👀

**Comment by liamjones** [comment]
@nickfujita I'd suggest trying the website/email address at the top of https://github.com/walmartlabs

**Pull request merged**
