### PR TITLE
[changelog] Fix missing and duplicate entries

### LINKED ISSUE #160: [changelog] Missing and duplicate entries
Related to [this card](https://github.com/react-native-community/discussions-and-proposals/projects/1#card-31964640).

There are currently a few issues with the changelog generator:

* No more than 250 commits are considered due to GitHub’s [“compare commits” API](https://developer.github.com/v3/repos/commits/#compare-two-commits) being used. This should be replaced by usage of an API that is able to iterate over long commit ranges and require an authentication token, for the user running the script, to allow paginating through all the commits.

* Because of how RN’s release process works, we cannot simply use git’s history to inform the generator on what changes should be included in the changelog.

  The reason being that cherry-picked commits are new changes, as far as git is concerned, and may thus be picked up again in subsequent releases. (For a reproduction of this issue, see [this example](https://github.com/alloy/RNBranchingStrategyRepro/compare/v1...v2). The `v1` commit is not expected to show up in this diff, as it was picked for `v1`, yet there it is.)

  After having slept on it for a few days, I think the best way to solve this is to:
  1. Use the “differential revision” that FB’s infrastructure adds to each commit to find the SHA of the commit in `master`, then;
  1. check if that SHA already exists in the changelog, in which case it is skipped, or otherwise;
  1. add the entry to the changelog with the commit SHA as it exists in `master`, rather than the stable branch.
  1. Finally, when invoking the generator, compare the current `0.x-stable` branch against the commit from which the _previous_ `0.x-stable` branch was forked off of `master`–as not all commits in `master` since then will have been included in the previous release.

TL;DR Use the `master` commit ref as canonical and check for its existence in the changelog to decide wether or not to include it.

### PR DESCRIPTION
**Pull request by alloy**
Closes #160 

* Commits are resolved to their original commit SHA as they exist in `master`.
* Ensure we start from the place where the previous version was branched off of `master`.
* Authenticated pagination is added in order to pull in all the changes.
* Adds some rudimentary tests for the places I touched.
* Output is cleaned up, colorized, and all logs go to `stderr`.
   Screenshot 2020-02-27 at 21 19 29

Finally, [here’s an example of the logs](https://gist.github.com/alloy/43896e2d82b6e2c99e5e85eb713b0306#file-stderr-txt) and [here’s an example of the generated markdown](https://gist.github.com/alloy/43896e2d82b6e2c99e5e85eb713b0306#file-stdout-md). As you can see, there’s a lot more entries there than in [the one](https://github.com/react-native-community/releases/blob/94ec57b525f1389608bddcd71193e99302f08e96/CHANGELOG.md) that’s currently [PR’ed](https://github.com/react-native-community/releases/pull/156).

You can run that locally with:

```bash
yarn generate -b v0.61.5 -c v0.62.0-rc.3 -r path/to/react-native/repo -f ./CHANGELOG.md -t [GITHUB-TOKEN]
```

## Follow-up work:

* There’s a lot of entries that are not being parsed and formatted correctly.
* The revert commits that are missing their “mate” are not being logged well, but I was hesitant to touch this code without test coverage. @turnrye Are you up for adding some test coverage for the current state of `filterRevertCommits`?
   Screenshot 2020-02-27 at 21 10 42

### CODE REVIEW

**Comment by alloy** [comment]
Alright, this should be finished and good to review. The last commit that I will add to this PR before merging is to update the last MINOR version CHANGELOG entries to use canonical master commits.

**Comment by alloy** [comment]
All done ✨

**Comment by kelset** [comment]
I'm really grateful that you managed to work on this Eloy, this PR looks awesome and it's so so helpful 🙇‍♂️

I'll be checking it out more closely tomorrow, in the meantime I've added Eli to the reviewers since he also worked on the script.

One thing I've noticed is that some entries still retain variations on `Changelog: [iOS] [Fixed]` tags instead of the titles but I guess it's normal and we can handle those manually post generation. 

---

Btw in particular this line `Changelog: [iOS] [Fixed] (cb80e3b by @priteshrnandgaonkar)` doesn't have any actual info about the commit but if I click on the hash to go back to the main repo it's 404-ing me...?

**Comment by TheSavior** [comment]
Seems good enough to iterate from as we make more improvements!

**Comment by alloy** [comment]
> Btw in particular this line `Changelog: [iOS] [Fixed] (cb80e3b by @priteshrnandgaonkar)` doesn't have any actual info about the commit but if I click on the hash to go back to the main repo it's 404-ing me...?

@kelset Ooh, interesting, happy birthday problem! Looks like RN is already too large to shorten hashes to 7 characters 😱 The actual hash is [cb80e3b599d0a781af8ad2999c4f1b58a11de05f](https://github.com/facebook/react-native/commit/cb80e3b599d0a781af8ad2999c4f1b58a11de05f), when shortened to 8 characters it will work, but when shortened to 7 it cannot be found (which I _assume_ means GH encountered a collision). 

```bash
$ git show cb80e3b
error: short SHA1 cb80e3b is ambiguous
hint: The candidates are:
hint:   cb80e3b599 commit 2020-02-12 - @allow-large-files [Flipper][RN] Integrated Flipper in RNTester application
hint:   cb80e3b388 tree
```

We can either pick an arbitrary larger number or just not shorten. I’m in favour of the simple thing, which would be to just use the full hashes. Opinions?

**Comment by alloy** [comment]
I was thinking that perhaps GitHub would truncate them for us, but seeing as the changelog isn’t even in the same repo that definitely won’t work. In that case let’s truncate the hashes to 10 chars _for display only_ and use full hashes for the links.

**Comment by kelset** [comment]
> In that case let’s truncate the hashes to 10 chars for display only and use full hashes for the links.
sounds great 👍

**Pull request merged**
